#!/usr/bin/env zsh
# ABOUTME: Configures macOS remote access services for Screen Sharing, SSH, and file sharing
# ABOUTME: Implements secure remote access setup with proper authentication and network discovery

#=============================================================================
# SCRIPT: remote-access.zsh
# AUTHOR: macOS Setup System
# DATE: 2025-01-07
# VERSION: 1.0.0
# 
# DESCRIPTION:
#   Configures macOS remote access services including Screen Sharing, SSH,
#   and file sharing with security hardening and network optimisation
#
# USAGE:
#   source remote-access.zsh
#   configure_remote_access
#
# REQUIREMENTS:
#   - macOS 11.0+ (Big Sur)
#   - Administrator privileges
#   - Network connectivity for testing
#
# NOTES:
#   - Implements security best practices
#   - Optimised for Apple Silicon Macs
#   - Includes network discovery and health monitoring
#=============================================================================

# Source common utilities
source "${0:A:h}/../lib/dry-run-utils.zsh"

# Remote access constants
readonly REMOTE_ACCESS_LOG_FILE="/tmp/remote-access-setup.log"
readonly SSH_CONFIG_DIR="$HOME/.ssh"
readonly SSH_CONFIG_FILE="$SSH_CONFIG_DIR/config"
readonly KNOWN_HOSTS_FILE="$SSH_CONFIG_DIR/known_hosts"

#=============================================================================
# SCREEN SHARING CONFIGURATION
#=============================================================================

configure_screen_sharing() {
    info "Configuring Screen Sharing (VNC)..."
    
    # Enable Screen Sharing
    execute_with_dry_run "sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist" \
        "Enable Screen Sharing service"
    
    # Configure Screen Sharing settings
    execute_with_dry_run "sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.screensharing -dict Disabled -bool false" \
        "Configure Screen Sharing in launch daemon overrides"
    
    # Set VNC password (prompt user for security)
    if [[ $DRY_RUN != "true" ]]; then
        echo -n "Set VNC password for Screen Sharing (leave blank to skip): "
        read -rs vnc_password
        echo
        
        if [[ -n "$vnc_password" ]]; then
            echo "$vnc_password" | sudo tee /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -h /var/db/dslocal/nodes/Default/config/VNCPassword.plist > /dev/null
            info "VNC password set for Screen Sharing"
        fi
    else
        echo "[DRY RUN] Would prompt for VNC password"
    fi
    
    # Configure Screen Sharing security settings
    execute_with_dry_run "sudo defaults write /Library/Preferences/com.apple.RemoteDesktop.plist VNCLegacyConnectionsEnabled -bool false" \
        "Disable legacy VNC connections for security"
    
    execute_with_dry_run "sudo defaults write /Library/Preferences/com.apple.RemoteDesktop.plist VNCAlwaysStartOnConsole -bool true" \
        "Always start VNC on console"
    
    # Allow Screen Sharing through firewall
    execute_with_dry_run "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent" \
        "Allow Screen Sharing through firewall"
    
    execute_with_dry_run "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent" \
        "Unblock Screen Sharing in firewall"
    
    success "Screen Sharing configured"
}

#=============================================================================
# SSH CONFIGURATION
#=============================================================================

configure_ssh_server() {
    info "Configuring SSH server..."
    
    # Enable SSH (Remote Login)
    execute_with_dry_run "sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist" \
        "Enable SSH service"
    
    execute_with_dry_run "sudo systemsetup -setremotelogin on" \
        "Enable Remote Login in System Preferences"
    
    # Configure SSH daemon settings
    local sshd_config="/etc/ssh/sshd_config"
    
    if [[ $DRY_RUN != "true" ]]; then
        # Backup original config
        if [[ ! -f "${sshd_config}.backup" ]]; then
            sudo cp "$sshd_config" "${sshd_config}.backup"
            info "Backed up original SSH config"
        fi
        
        # Create hardened SSH configuration
        sudo tee "$sshd_config" > /dev/null << 'EOF'
# Hardened SSH configuration for macOS
# Generated by macOS Setup System

# Basic settings
Port 22
Protocol 2
AddressFamily any
ListenAddress 0.0.0.0
ListenAddress ::

# Security settings
PermitRootLogin no
PasswordAuthentication yes
ChallengeResponseAuthentication no
UsePAM yes
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Connection settings
ClientAliveInterval 300
ClientAliveCountMax 2
MaxAuthTries 3
MaxSessions 10
LoginGraceTime 120

# Disable unused authentication methods
KerberosAuthentication no
GSSAPIAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no

# Logging
SyslogFacility AUTH
LogLevel INFO

# Subsystem configuration
Subsystem sftp /usr/libexec/sftp-server

# macOS specific settings
UsePrivilegeSeparation sandbox
Compression delayed
UseDNS no
EOF
        
        info "SSH daemon configuration updated"
    else
        echo "[DRY RUN] Would update SSH daemon configuration"
    fi
    
    # Restart SSH service
    execute_with_dry_run "sudo launchctl stop com.openssh.sshd" \
        "Stop SSH service"
    
    execute_with_dry_run "sudo launchctl start com.openssh.sshd" \
        "Start SSH service"
    
    success "SSH server configured"
}

setup_ssh_keys() {
    info "Setting up SSH keys..."
    
    # Create SSH directory if it doesn't exist
    execute_with_dry_run "mkdir -p '$SSH_CONFIG_DIR'" \
        "Create SSH configuration directory"
    
    execute_with_dry_run "chmod 700 '$SSH_CONFIG_DIR'" \
        "Set SSH directory permissions"
    
    # Generate SSH key if it doesn't exist
    if [[ ! -f "$SSH_CONFIG_DIR/id_ed25519" ]]; then
        if [[ $DRY_RUN != "true" ]]; then
            echo -n "Generate new SSH key? (y/n): "
            read -r generate_key
            
            if [[ "$generate_key" == "y" || "$generate_key" == "Y" ]]; then
                echo -n "Enter email for SSH key: "
                read -r ssh_email
                
                ssh-keygen -t ed25519 -C "$ssh_email" -f "$SSH_CONFIG_DIR/id_ed25519" -N ""
                info "Generated new SSH key"
                
                # Set proper permissions
                chmod 600 "$SSH_CONFIG_DIR/id_ed25519"
                chmod 644 "$SSH_CONFIG_DIR/id_ed25519.pub"
                
                # Display public key
                echo
                info "Your public SSH key:"
                cat "$SSH_CONFIG_DIR/id_ed25519.pub"
                echo
                info "Add this key to your other machines' ~/.ssh/authorized_keys"
            fi
        else
            echo "[DRY RUN] Would generate SSH key if requested"
        fi
    else
        success "SSH key already exists"
    fi
    
    # Create SSH config file
    if [[ ! -f "$SSH_CONFIG_FILE" ]]; then
        execute_with_dry_run "touch '$SSH_CONFIG_FILE'" \
            "Create SSH client config file"
        
        execute_with_dry_run "chmod 600 '$SSH_CONFIG_FILE'" \
            "Set SSH config file permissions"
    fi
    
    success "SSH keys configured"
}

#=============================================================================
# FILE SHARING CONFIGURATION
#=============================================================================

configure_file_sharing() {
    info "Configuring file sharing services..."
    
    # Enable AFP (Apple Filing Protocol)
    execute_with_dry_run "sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.AppleFileServer.plist" \
        "Enable AFP file sharing"
    
    # Enable SMB (Server Message Block)
    execute_with_dry_run "sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.smbd.plist" \
        "Enable SMB file sharing"
    
    # Configure SMB settings
    execute_with_dry_run "sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server.plist NetBIOSName -string '$(hostname -s)'" \
        "Set SMB NetBIOS name"
    
    execute_with_dry_run "sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server.plist ServerDescription -string 'macOS File Server'" \
        "Set SMB server description"
    
    # Create default shared directories
    local shared_dir="$HOME/Shared"
    execute_with_dry_run "mkdir -p '$shared_dir'" \
        "Create shared directory"
    
    execute_with_dry_run "chmod 755 '$shared_dir'" \
        "Set shared directory permissions"
    
    # Configure sharing permissions
    if [[ $DRY_RUN != "true" ]]; then
        # Enable sharing for current user
        sudo sharing -a "$shared_dir" -S "Shared" -s 001 -g 000
        info "Configured file sharing for $shared_dir"
    else
        echo "[DRY RUN] Would configure file sharing permissions"
    fi
    
    success "File sharing configured"
}

#=============================================================================
# NETWORK DISCOVERY CONFIGURATION
#=============================================================================

configure_network_discovery() {
    info "Configuring network discovery and Bonjour..."
    
    # Enable Bonjour advertisement
    execute_with_dry_run "sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server.plist EnabledServices -array disk" \
        "Enable Bonjour SMB advertisement"
    
    # Configure mDNS responder
    execute_with_dry_run "sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist" \
        "Enable mDNS responder"
    
    # Set computer name for network discovery
    local computer_name
    computer_name=$(hostname -s)
    
    execute_with_dry_run "sudo scutil --set ComputerName '$computer_name'" \
        "Set computer name"
    
    execute_with_dry_run "sudo scutil --set HostName '$computer_name.local'" \
        "Set hostname"
    
    execute_with_dry_run "sudo scutil --set LocalHostName '$computer_name'" \
        "Set local hostname"
    
    # Configure network service order
    execute_with_dry_run "sudo networksetup -ordernetworkservices 'Wi-Fi' 'Ethernet'" \
        "Set network service order"
    
    success "Network discovery configured"
}

#=============================================================================
# FIREWALL CONFIGURATION
#=============================================================================

configure_firewall() {
    info "Configuring firewall for remote access..."
    
    # Enable firewall
    execute_with_dry_run "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on" \
        "Enable application firewall"
    
    # Configure firewall logging
    execute_with_dry_run "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on" \
        "Enable firewall logging"
    
    # Allow signed applications
    execute_with_dry_run "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsigned on" \
        "Allow signed applications through firewall"
    
    # Enable stealth mode
    execute_with_dry_run "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on" \
        "Enable firewall stealth mode"
    
    # Allow specific services
    local services=("ssh" "vnc-server" "afp" "smb")
    
    for service in "${services[@]}"; do
        execute_with_dry_run "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add '$service'" \
            "Allow $service through firewall"
        
        execute_with_dry_run "sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblock '$service'" \
            "Unblock $service in firewall"
    done
    
    success "Firewall configured for remote access"
}

#=============================================================================
# HEALTH MONITORING
#=============================================================================

test_remote_access() {
    info "Testing remote access connectivity..."
    
    local hostname
    hostname=$(hostname)
    
    # Test SSH
    if [[ $DRY_RUN != "true" ]]; then
        if nc -z localhost 22; then
            success "SSH service is running on port 22"
        else
            warn "SSH service is not accessible"
        fi
        
        # Test VNC
        if nc -z localhost 5900; then
            success "VNC service is running on port 5900"
        else
            warn "VNC service is not accessible"
        fi
        
        # Test SMB
        if nc -z localhost 445; then
            success "SMB service is running on port 445"
        else
            warn "SMB service is not accessible"
        fi
        
        # Test AFP
        if nc -z localhost 548; then
            success "AFP service is running on port 548"
        else
            warn "AFP service is not accessible"
        fi
    else
        echo "[DRY RUN] Would test remote access connectivity"
    fi
    
    # Display connection information
    echo
    info "Remote Access Information:"
    echo "  Hostname: $hostname"
    echo "  SSH:      ssh $(whoami)@$hostname"
    echo "  VNC:      vnc://$hostname:5900"
    echo "  SMB:      smb://$hostname"
    echo "  AFP:      afp://$hostname"
    echo
    
    # Network interface information
    if [[ $DRY_RUN != "true" ]]; then
        echo "Network Interfaces:"
        ifconfig | grep -E "inet [0-9]" | grep -v "127.0.0.1" | while read -r line; do
            local ip
            ip=$(echo "$line" | awk '{print $2}')
            echo "  IP Address: $ip"
        done
    else
        echo "[DRY RUN] Would display network interface information"
    fi
}

monitor_remote_access() {
    info "Monitoring remote access services..."
    
    if [[ $DRY_RUN != "true" ]]; then
        echo "=== Active Remote Access Services ==="
        
        # Check SSH
        if pgrep -q sshd; then
            echo "✓ SSH (sshd) is running"
            echo "  Connections: $(who | grep -v console | wc -l | xargs)"
        else
            echo "✗ SSH (sshd) is not running"
        fi
        
        # Check Screen Sharing
        if pgrep -q ARDAgent; then
            echo "✓ Screen Sharing (ARDAgent) is running"
        else
            echo "✗ Screen Sharing (ARDAgent) is not running"
        fi
        
        # Check file sharing
        if pgrep -q smbd; then
            echo "✓ SMB file sharing is running"
        else
            echo "✗ SMB file sharing is not running"
        fi
        
        if pgrep -q AppleFileServer; then
            echo "✓ AFP file sharing is running"
        else
            echo "✗ AFP file sharing is not running"
        fi
        
        echo
        echo "=== Network Connections ==="
        netstat -an | grep LISTEN | grep -E "(22|445|548|5900)"
        
        echo
        echo "=== Recent Connection Attempts ==="
        sudo tail -20 /var/log/system.log | grep -E "(ssh|vnc|smb|afp)"
        
    else
        echo "[DRY RUN] Would display remote access service status"
    fi
}

#=============================================================================
# MAIN CONFIGURATION FUNCTION
#=============================================================================

configure_remote_access() {
    info "Configuring remote access services..."
    
    # Validate we have the necessary permissions
    if [[ $DRY_RUN != "true" ]] && ! sudo -n true 2>/dev/null; then
        warn "Administrator privileges required for remote access configuration"
        info "Please run: sudo -v"
        return 1
    fi
    
    # Configure Screen Sharing
    configure_screen_sharing
    
    # Configure SSH
    configure_ssh_server
    setup_ssh_keys
    
    # Configure file sharing
    configure_file_sharing
    
    # Configure network discovery
    configure_network_discovery
    
    # Configure firewall
    configure_firewall
    
    # Test connectivity
    test_remote_access
    
    success "Remote access configuration complete"
    
    # Provide user guidance
    echo
    info "Remote Access Summary:"
    echo "  • Screen Sharing (VNC) enabled on port 5900"
    echo "  • SSH enabled on port 22 with hardened configuration"
    echo "  • SMB file sharing enabled on port 445"
    echo "  • AFP file sharing enabled on port 548"
    echo "  • Firewall configured with necessary exceptions"
    echo "  • Network discovery and Bonjour enabled"
    echo
    
    info "Security Recommendations:"
    echo "  • Use SSH keys instead of passwords where possible"
    echo "  • Set strong VNC password for Screen Sharing"
    echo "  • Regularly update system and monitor access logs"
    echo "  • Consider VPN for remote access over internet"
    echo
    
    info "Next Steps:"
    echo "  • Test connectivity from other devices"
    echo "  • Monitor services with: monitor_remote_access"
    echo "  • Check logs regularly for security"
}

#=============================================================================
# UTILITY FUNCTIONS
#=============================================================================

disable_remote_access() {
    info "Disabling remote access services..."
    
    # Disable Screen Sharing
    execute_with_dry_run "sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.screensharing.plist" \
        "Disable Screen Sharing"
    
    # Disable SSH
    execute_with_dry_run "sudo systemsetup -setremotelogin off" \
        "Disable SSH"
    
    # Disable file sharing
    execute_with_dry_run "sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.AppleFileServer.plist" \
        "Disable AFP"
    
    execute_with_dry_run "sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.smbd.plist" \
        "Disable SMB"
    
    success "Remote access services disabled"
}

remote_access_help() {
    cat << EOF
${BOLD}Remote Access Configuration${RESET}

${BOLD}USAGE${RESET}
    configure_remote_access       Configure all remote access services
    disable_remote_access        Disable all remote access services
    test_remote_access           Test remote access connectivity
    monitor_remote_access        Monitor remote access services

${BOLD}SERVICES CONFIGURED${RESET}
    Screen Sharing (VNC):
        • Port 5900
        • Secure VNC password
        • Firewall exceptions

    SSH:
        • Port 22
        • Hardened configuration
        • Key-based authentication

    File Sharing:
        • SMB on port 445
        • AFP on port 548
        • Bonjour discovery

${BOLD}SECURITY FEATURES${RESET}
    • Application firewall enabled
    • Stealth mode activated
    • Signed applications allowed
    • SSH key generation
    • Connection monitoring

${BOLD}EXAMPLES${RESET}
    # Configure all services
    configure_remote_access

    # Test connectivity
    test_remote_access

    # Monitor services
    monitor_remote_access

    # Disable all services
    disable_remote_access
EOF
}

# Export functions for use in other scripts
autoload -U configure_remote_access
autoload -U disable_remote_access
autoload -U test_remote_access
autoload -U monitor_remote_access
autoload -U remote_access_help